var appTitle = 'Sajjad Hossain | Novelist, Artisan, Entrepreneur',
    qaEmail = 'sajjad@withpulp.com',
    qaPassword = 'Knight22';

module.exports = {
    qaEmail: qaEmail,
    qaPassword: qaPassword,
    appTitle: appTitle,
    step8Header: '#step8',
    step8HeaderText: 'STEP 8',
    bottom: '#bottom',
    formDiv: '#footer-form',
    form: '#contact',
    nameInput: '#name',
    nameInputValue: 'Ra\'s Al-Ghoul',
    emailInput: '#email',
    emailInputValue: 'ras@infinitytech.com',
    messageInput:'#message',
    messageInputValue: 'Infinity Technology is heavily interested in your profile.',
    job1Title: '#wayneEnterprises-jobTitle',
    job1TitleValue: 'CEO',
    job2Title: '#batmanIncorporated-jobTitle',
    job2TitleValue: 'Co-Founder',
    job3Title: '#starbucks-jobTitle',
    job3TitleValue: 'Barista',
    job1From: '#wayneEnterprises-jobFrom',
    job1FromValue: '2002',
    job2From: '#batmanIncorporated-jobFrom',
    job2FromValue: '2010',
    job3From: '#starbucks-jobFrom',
    job3FromValue: '2006',
    job1To: '#wayneEnterprises-jobTo',
    job1ToValue: 'Present',
    job2To: '#batmanIncorporated-jobTo',
    job2ToValue: 'Present',
    job3To: '#starbucks-jobTo',
    job3ToValue: '2009',
    job1Logo: '#wayneEnterprises-jobLogo',
    job1LogoValue: 'http://localhost:3000/images/wayne-enterprises-logo.png',
    job2Logo: '#batmanIncorporated-jobLogo',
    job2LogoValue: 'http://localhost:3000/images/batman-inc-logo.png',
    job3Logo: '#starbucks-jobLogo',
    job3LogoValue: 'http://localhost:3000/images/starbucks-logo.png',
    job1Location: '#wayneEnterprises-jobLocation',
    job1LocationValue: 'Gotham, NY',
    job2Location: '#batmanIncorporated-jobLocation',
    job2LocationValue: 'Gotham, NY',
    job3Location: '#starbucks-jobLocation',
    job3LocationValue: 'Gotham, NY',
    job1Additional: '#wayneEnterprises-jobAdditional',
    job1AdditionalValue: 'Acquired by Wayne, Inc.',
    job2Additional: '#batmanIncorporated-jobAdditional',
    job2AdditionalValue: 'Mentioned in TIME',
    job3Additional: '#starbucks-jobAdditional',
    job3AdditionalValue: '',
    job1Description: '#wayneEnterprises-jobDescription',
    job1DescriptionValue: 'Hero can be anyone. Even a man knowing something as simple and reassuring as putting a coat around a young boy shoulders to let him know the world hadn\'t ended.',
    job2Description: '#batmanIncorporated-jobDescription',
    job2DescriptionValue: 'But we\'ve met before. That was a long time ago, I was a kid at St. Swithin\'s, It used to be funded by the Wayne Foundation. It\'s an orphanage. My mum died when I was small, it was a car accident. I don\'t remember it. My dad got shot a couple of years later for a gambling debt. Oh I remember that one just fine. Not a lot of people know what it feels like to be angry in your bones. I mean they understand.',
    job3Description: '#starbucks-jobDescription',
    job3DescriptionValue: 'This position contributes to Starbucks success by providing legendary customer service to all customers. This job creates the Starbucks Experience for our customers by providing customers with prompt service, quality beverages and products, and maintaining a clean and comfortable store environment. Models and acts in accordance with Starbucks guiding principles.',
    //job1Bullet1: '#wayneEnterprises-jobBullet1',
    //job1Bullet1Value: 'Present',
    //job2Bullet1: '#batmanIncorporated-jobBullet1',
    //job2Bullet1Value: 'Present',
    //job3Bullet1: '#starbucks-jobBullet1',
    //job3Bullet1Value: '2009',
    //job1Bullet2: '#wayneEnterprises-jobBullet2',
    //job1Bullet2Value: 'Present',
    //job2Bullet2: '#batmanIncorporated-jobBullet2',
    //job2Bullet2Value: 'Present',
    //job3Bullet2: '#starbucks-jobBullet2',
    //job3Bullet2Value: '2009',
    //job1Bullet3: '#wayneEnterprises-jobBullet3',
    //job1Bullet3Value: 'Present',
    //job2Bullet3: '#batmanIncorporated-jobBullet3',
    //job2Bullet3Value: 'Present',
    //job3Bullet3: '#starbucks-jobBullet3',
    //job3Bullet3Value: '2009',
    submit: '#submit',
    submitDetails: '#submitDetails'
};
