var appTitle = 'Sajjad Hossain | Novelist, Artisan, Entrepreneur',
    qaEmail = 'sajjad@withpulp.com',
    qaPassword = 'Knight22';

module.exports = {
    qaEmail: qaEmail,
    qaPassword: qaPassword,
    appTitle: appTitle,
    step8Header: '#step8',
    step8HeaderText: 'STEP 8',
    bottom: '#bottom',
    formDiv: '#footer-form',
    form: '#contact',
    nameInput: '#name',
    nameInputValue: 'Ra\'s Al-Ghoul',
    emailInput: '#email',
    emailInputValue: 'ras@infinitytech.com',
    messageInput:'#message',
    messageInputValue: 'Infinity Technology is heavily interested in your profile.',
    job1Title: '#wayneEnterprises-jobTitle',
    job1TitleValue: 'CEO',
    job2Title: '#batmanInc-jobTitle',
    job2TitleValue: 'Co-Founder',
    job3Title: '#starbucks-jobTitle',
    job3TitleValue: 'Barista',
    job1Website: '#wayneEnterprises-jobWebsite',
    job1WebsiteValue: 'http://wayneenterprises.com',
    job2Website: '#batmanInc-jobWebsite',
    job2WebsiteValue: 'http://batmaninc.com',
    job3Website: '#starbucks-jobWebsite',
    job3WebsiteValue: 'http://starbucks.com',
    job1From: '#wayneEnterprises-jobFrom',
    job1FromValue: '02',
    job2From: '#batmanInc-jobFrom',
    job2FromValue: '10',
    job3From: '#starbucks-jobFrom',
    job3FromValue: '06',
    job1To: '#wayneEnterprises-jobTo',
    job1ToValue: 'Present',
    job2To: '#batmanInc-jobTo',
    job2ToValue: 'Present',
    job3To: '#starbucks-jobTo',
    job3ToValue: '09',
    job1Logo: '#wayneEnterprises-jobLogo',
    job1LogoValue: 'http://localhost:3000/images/wayne-enterprises-logo.png',
    job2Logo: '#batmanInc-jobLogo',
    job2LogoValue: 'http://localhost:3000/images/batman-inc-logo.png',
    job3Logo: '#starbucks-jobLogo',
    job3LogoValue: 'http://localhost:3000/images/starbucks-logo.png',
    job1Location: '#wayneEnterprises-jobLocation',
    job1LocationValue: 'Gotham, NY',
    job2Location: '#batmanInc-jobLocation',
    job2LocationValue: 'Gotham, NY',
    job3Location: '#starbucks-jobLocation',
    job3LocationValue: 'Gotham, NY',
    job1Additional: '#wayneEnterprises-jobAdditional',
    job1AdditionalValue: 'Acquired by Wayne, Inc.',
    job2Additional: '#batmanInc-jobAdditional',
    job2AdditionalValue: 'Mentioned in TIME',
    job3Additional: '#starbucks-jobAdditional',
    job3AdditionalValue: '',
    job1Description: '#wayneEnterprises-jobDescription',
    job1DescriptionValue: 'I can be ignored, destroyed. But as a symbol...',
    job2Description: '#batmanInc-jobDescription',
    job2DescriptionValue: 'But we\'ve met before. That was a long time ago, I was a kid at St. Swithin\'s, It used to be funded by the Wayne Foundation. It\'s an orphanage. My mum died when I was small, it was a car accident. I don\'t remember it. My dad got shot a couple of years later for a gambling debt. Oh I remember that one just fine. Not a lot of people know what it feels like to be angry in your bones. I mean they understand.',
    job3Description: '#starbucks-jobDescription',
    job3DescriptionValue: 'This position contributes to Starbucks success by providing legendary customer service to all customers. This job creates the Starbucks Experience for our customers by providing customers with prompt service, quality beverages and products, and maintaining a clean and comfortable store environment. Models and acts in accordance with Starbucks guiding principles.',
    job1AddBullet: '.wayneEnterprises-addBullet',
    job2AddBullet: '.batmanInc-addBullet',
    job3AddBullet: '.starbucks-addBullet',
    job1Bullet1: '#wayneEnterprises-bullet0',
    job1Bullet1Value: 'I\'ll be standing where l belong. Between you and the peopIe of Gotham.',
    job1Bullet2: '#wayneEnterprises-bullet1',
    job1Bullet2Value: 'Behind you, stands a symbol of oppression. Blackgate Prison, where a thousand men have languished under the name of this man: Harvey Dent.',
    job1Bullet3: '#wayneEnterprises-bullet2',
    job1Bullet3Value: 'But no ordinary child, a child born in hell, forged from suffering, hardened by pain. Not a man from privilege.',
    job2Bullet1: '#batmanInc-bullet0',
    job2Bullet1Value: 'Peace has cost you your strength. Victory has defeated you.',
    job2Bullet2: '#batmanInc-bullet1',
    job2Bullet2Value: 'Gotham\'s time has come.',
    job3Bullet1: '#starbucks-bullet0',
    job3Bullet1Value: 'Gordon... You do like to play things pretty close to the chest.',
    job3Bullet2: '#starbucks-bullet1',
    job3Bullet2Value: 'I can\'t do that as Bruce Wayne... as a man. I\'m flesh and blood.',
    job3Bullet3: '#starbucks-bullet2',
    job3Bullet3Value: 'I can be incorruptible, I can be everlasting.',
    submit: '#submit',
    submitDetails: '#submitDetails'
};
