var appTitle = 'Build Your Resumé',
    qaEmail = 'sajjad@withpulp.com',
    qaPassword = 'Knight22';

module.exports = {
    qaEmail: qaEmail,
    qaPassword: qaPassword,
    appTitle: appTitle,
    controls: '#controls',
    buildHeader: '#reumeBuilderHeader',
    buildHeaderText: 'RESUMÉ BUILDER',
    stepHeader1: '#step1',
    stepHeader2: '#step2',
    stepHeader3: '#step3',
    stepHeader4: '#step4',
    stepHeader5: '#step5',
    stepHeader1Text: 'STEP 1',
    stepHeader2Text: 'STEP 2',
    stepHeader3Text: 'STEP 3',
    stepHeader4Text: 'STEP 4',
    stepHeader5Text: 'STEP 5',
    themeYourResume: '#themeYourResume',
    themeYourResumeText: 'Theme your resumé',
    createYourProfile: '#createYourProfile',
    createYourProfileText: 'Create your profile',
    supplyYourMission: '#supplyYourMission',
    supplyYourMissionText: 'Supply your mission',
    addSkills: '#addSkills',
    addSkillsText: 'Add skills',
    workExperience: '#workExperience',
    workExperienceText: 'Work experience',
    pickAColor: 'a[data-activates="dropdown1"]',
    pickPink: 'li.pink',
    backgroundImageInput: '#backgroundImage',
    backgroundImageInputValue: 'http://localhost:3000/images/batman.jpg',
    colorPreview: '#colorPreview',
    pinkColorPreview: 'pink white-text card-panel',
    firstNameInput: '#firstName',
    firstNameInputValue: 'Bruce',
    lastNameInput: '#lastName',
    lastNameInputValue: 'Wayne',
    emailInput: '#email',
    emailInputValue: 'bwayne@wayneenterprises.com',
    phoneInput: '#phone',
    phoneInputValue: '347-734-7434',
    githubInput: '#github',
    githubInputValue: 'darkknight',
    gmailInput: '#gmail',
    gmailInputValue: 'bwayne@gmail.com',
    passwordInput: '#password',
    passwordInputValue: 'batcave',
    objectiveInput: 'textarea[id="objective"]',
    objectiveInputValue: 'Sometimes, I admit, I think of Bruce as a man in a costume. Then, with some gadget from his utility belt, he reminds me that he has an extraordinarily inventive mind. And how lucky I am to be able to call on him.',
    addSkill: "#addSkill",
    skillName1Input: '#skillName1',
    skillName1InputValue: 'Detective',
    skillPercent1Input: '#skillPercent1',
    skillPercent1InputValue: '99',
    skillDetail1Input: '#skillDetail1',
    skillDetail1InputValue: 'Database, Searching, Forensic Science, Scene Recreation, Statistical Probability',
    skillName2Input: '#skillName2',
    skillName2InputValue: 'Martial Arts',
    skillPercent2Input: '#skillPercent2',
    skillPercent2InputValue: '99',
    skillDetail2Input: '#skillDetail2',
    skillDetail2InputValue: 'Judo, Self Defense, Ninja Assassin',
    job1Input: 'input[name="job1"]',
    job1InputValue: 'Wayne Enterprises',
    job2Input: 'input[name="job2"]',
    job2InputValue: 'Batman Inc.',
    job3Input: 'input[name="job3"]',
    job3InputValue: 'Starbucks',
    bullet: "#bullet",
    buildMyShyt: '#buildMyShyt'
};
