var appTitle = 'Build Your Resumé',
    qaEmail = 'sajjad@withpulp.com',
    qaPassword = 'Knight22';

module.exports = {
    qaEmail: qaEmail,
    qaPassword: qaPassword,
    appTitle: appTitle,
    controls: '#controls',
    buildHeader: '#reumeBuilderHeader',
    buildHeaderText: 'RESUMÉ BUILDER',
    stepHeader1: '#step1',
    stepHeader2: '#step2',
    stepHeader3: '#step3',
    stepHeader4: '#step4',
    stepHeader5: '#step5',
    stepHeader6: '#step6',
    stepHeader7: '#step7',
    stepHeader1Text: 'STEP 1',
    stepHeader2Text: 'STEP 2',
    stepHeader3Text: 'STEP 3',
    stepHeader4Text: 'STEP 4',
    stepHeader5Text: 'STEP 5',
    stepHeader6Text: 'STEP 6',
    stepHeader7Text: 'STEP 7',
    themeYourResume: '#themeYourResume',
    themeYourResumeText: 'Theme your resumé',
    createYourProfile: '#createYourProfile',
    createYourProfileText: 'Create your profile',
    supplyYourMission: '#supplyYourMission',
    supplyYourMissionText: 'Supply your mission',
    addSkills: '#addSkills',
    addSkillsText: 'Add skills',
    addEducation: '#addEducation',
    addEducationText: 'Add Education',
    workExperience: '#workExperience',
    workExperienceText: 'Work experience',
    siteDetails: '#siteDetails',
    siteDetailsText: 'Site details',
    pickAColor: 'a[data-activates="dropdown1"]',
    pickPink: 'li.pink',
    backgroundImageInput: '#backgroundImage',
    backgroundImageInputValue: 'http://localhost:3000/images/batman.jpg',
    colorPreview: '#colorPreview',
    pinkColorPreview: 'pink white-text card-panel',
    firstNameInput: '#firstName',
    firstNameInputValue: 'Bruce',
    lastNameInput: '#lastName',
    lastNameInputValue: 'Wayne',
    emailInput: '#email',
    emailInputValue: 'bwayne@wayneenterprises.com',
    phoneInput: '#phone',
    phoneInputValue: '347-734-7434',
    githubInput: '#github',
    githubInputValue: 'darkknight',
    gmailInput: '#gmail',
    gmailInputValue: 'bwayne@gmail.com',
    passwordInput: '#password',
    passwordInputValue: 'batcave',
    objectiveInput: 'textarea[id="objective"]',
    objectiveInputValue: 'The first time I stole so that I wouldn\'t starve, yes. I lost many assumptions about the simple nature of right and wrong. And when I traveled I learned the fear before a crime and the thrill of success. But I never became one of them.',
    addSkill: "#addSkill",
    skillName1Input: '#skillName0',
    skillName1InputValue: 'Detective',
    skillPercent1Input: '#skillPercent0',
    skillPercent1InputValue: '99',
    skillDetail1Input: '#skillDetail0',
    skillDetail1InputValue: 'Database, Searching, Forensic Science, Scene Recreation, Statistical Probability',
    skillName2Input: '#skillName1',
    skillName2InputValue: 'Martial Arts',
    skillPercent2Input: '#skillPercent1',
    skillPercent2InputValue: '99',
    skillDetail2Input: '#skillDetail1',
    skillDetail2InputValue: 'Judo, Self Defense, Ninja Assassin',
    schoolName1Input: '#schoolName0',
    schoolName1InputValue: 'Gotham University for the Gifted',
    schoolLocation1Input: '#schoolLocation0',
    schoolLocation1InputValue: 'Gotham, NY',
    schoolStudy1Input: '#schoolStudy0',
    schoolStudy1InputValue: 'Master\'s in Business Administration',
    schoolFrom1Input: '#schoolFrom0',
    schoolTo1Input: '#schoolTo0',
    schoolFrom1InputValue: '\'98',
    schoolTo1InputValue: '\'02',
    hostInput: '#host',
    hostInputValue: 'http://localhost:3000',
    websiteInput: '#website',
    websiteInputValue: 'http://wayneenterprises.com',
    siteDescriptionInput: '#siteDescription',
    siteDescriptionInputValue: 'Batman, Billionaire, Vigilante',
    keywordsInput: '#keywords',
    keywordsInputValue: 'Super-Hero, Batman, Bruce Wayne, Billionaire, Playboy, Dark Knight, Christopher Nolan',
    job0Input: 'input[name="job0"]',
    job0InputValue: 'Wayne Enterprises',
    job1Input: 'input[name="job1"]',
    job1InputValue: 'Batman Incorporated',
    job2Input: 'input[name="job2"]',
    job2InputValue: 'Starbucks',
    job: ".add-job",
    buildMyShyt: '#buildMyShyt'
};
